/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const fluid_add_particles: (a: number, b: number, c: number, d: number) => void;
export const fluid_create_simulator: (a: number, b: number) => number;
export const fluid_get_particles: (a: number, b: number) => void;
export const fluid_read_pixels: (a: number, b: number) => void;
export const fluid_set_mask_rgba: (a: number, b: number, c: number) => void;
export const fluid_set_params: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => void;
export const get_agent_buffer_ptr: () => number;
export const get_params_buffer_ptr: () => number;
export const get_params_len: () => number;
export const get_sensing_buffer_ptr: () => number;
export const get_stride: () => number;
export const init_sensing: (a: number, b: number) => void;
export const remove_agent: (a: number) => void;
export const sim_init: (a: number, b: number, c: number) => void;
export const spawn_batch: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const update_sensing: () => void;
export const fluid_clear_particles: (a: number) => void;
export const step: (a: number) => void;
export const fluid_destroy_simulator: (a: number) => void;
export const fluid_get_particle_count: (a: number) => number;
export const get_agent_count: () => number;
export const clear_agents: () => void;
export const spawn_agent: (a: number, b: number) => number;
export const fluid_step: (a: number, b: number) => void;
export const set_params: () => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number) => void;
